import 'package:doctor_mymensingh/model/doctor_model.dart';
import 'package:flutter/cupertino.dart';

class DoctorRepo {
  List<DoctorModel> getallDoctorModelList = [
    DoctorModel(
        "hannan.jpg",
        "Burn Specialist",
        "Dr. Md Saidujjaman Jwel",
        "MBBS, FCPS",
        "Dept. Head, BIRDEM",
        "Modhumoti Diagnostic Centre",
        "3:00-6:00 PM",
        "Sun-Sat",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Dental Specialist",
        "Dr.  Jwel",
        "MBBS, FCPS",
        "Dept. Head, BIRDEM",
        "Modhumoti Diagnostic Centre",
        "3:00-6:00 PM",
        "Sun-Sat",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Urology Specialist",
        "Dr. Md. Afzalur Rahman",
        "Urology Specialist M, B, B, S (Dhaka), B, C, S (Health) M, S (Urology), U, R, C (Singapore) Trained in Laparoscopic Surgery Kidney, Urethral, ​​Bladder, Visit to Protest and Penis, Testicular and Urinary Tract Specialist and Surgeon National Institute of Kidney Diseases and Urology, Dhaka (X)",
        "Mymensingh Medical College and Hospital",
        "Swadesh Hospital (Pvt) Ltd",
        "3:00-6:00 PM",
        "Sun-Sat",
        "01734-92658",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Neurology Specialist",
        "Dr. Nurul Alam Bashar",
        "MBBS (Dhaka), BCS (Health) FCPS (Medicine) M, D (Neuromedicine) Medicine and Neurology",
        "BCS (Health) FCPS (Medicine)",
        "Swadesh Hospital (Pvt) Ltd",
        "3:00-6:00 PM",
        "Sun-Sat",
        "01734-92656",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Dermatology and Sexual Specialist",
        "Dr. Md. Moshiur Rahman",
        "MBBS, MCPS (Dermatology and Sexual), DDV, MD (Dermatology and Sexuality) Assistant Professor, Department of Dermatology and Venereal Diseases",
        "Mymensingh Medical College and Hospital",
        "Popular Diagnostic Center Ltd",
        "4.00 pm to 9 PM",
        "Sun-Sat",
        "01553-34172-83",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Nose Ear and Throat Specialist",
        "Dr. Samresh Chandra Kundu",
        "MBBS, FCPS (Nose, Ear and Throat) Nose, Ear and Throat Specialist and Surgeon Assistant Professor and Head of Department",
        "Mymensingh Medical College and Hospital",
        "Popular Diagnostic Center Ltd",
        " 4 pm .00 hrs to 8.00 hrs (closed on Fridays)",
        "Sun-Sat",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Diabetes Specialist",
        "Dr. Nazamul Karim Khan",
        "MBBS, DEM (Bardem) Assistant Professor of Diabetes, Thyroid, Hormone and Endocrine Medicine, Department of Diabetes and Endocrinology",
        "Mymensingh Medical College and Hospital",
        "(Popular Diagnostic Center Ltd.)",
        "5:00 pm. Closed on Thursdays and Fridays",
        "Sun-Sat",
        "01727-911555",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Neuroscientist Specialist",
        "Dr. kanoja Kumar Barman",
        "MBBS (III), MS-C, MPH, MD (neuroscientist) fellowship in epileptolaji (India), Japan and South Korea advanced training assistant professor (neuroscientist Division)",
        "Bangabandhu Sheikh Mujib Medical University (PG Hospital), Dhaka",
        "Popular Diagnostic Center Ltd,MymenSingh",
        "9:00 AM",
        "Sun-Sat",
        "01553-34172-63",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Medicine Specialist",
        "Chittaranjan Debnath",
        "MBBS, FCPS (Medicine) MD (Hepatology) MACP (USA) FRCP (Edin) UK Liver and Medicine Specialist",
        "Mymensingh Medical College and Hospital",
        "Popular Diagnostic Center Ltd",
        "3:00-6:00 PM",
        "Sun-Sat",
        "01553-34172-73",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Cardiology Specialist",
        "Prof. Dr. M. Shamsul Haque",
        "MBBS.M, DM (Cardiology) Former Head of Department (Retd.)",
        "Cardiology Mymensingh Medical College and Hospital",
        "Popular Diagnostic Center Ltd",
        "8.30 am to 6.00 pm",
        "Sun-Sat",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Surgery Specialist",
        "Dr. Afroza Islam",
        "MBBS (Dhaka), BCS (Health) FCPS Surgery Consultant (Surgery) Surgery Specialist",
        "Cardiology Mymensingh Medical College and Hospital",
        "Nexus Hospital",
        "5pm to 8pm",
        "Saturday to Thursday ",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Child Specialist",
        "Dr. Mili Rahman",
        "MBBS Child, Surgery Specialist",
        "Mymensingh Medical College and Hospital",
        "Nexus Hospital",
        "5pm to 8pm",
        "Saturday to Thursday ",
        "+01977756258",
        "600"),
    DoctorModel(
        "hannan.jpg",
        "Ent Specialist",
        "Dr. Saiket Islam",
        "MBBS (Dhaka), BCS (Health)",
        " Mymensingh Medical College and Hospital",
        "Nexus Hospital",
        "5pm to 8pm",
        "Saturday to Thursday ",
        "+01977756258",
        "600"),
  ];
}
